rtl/fa_pkg.sv
rtl/fa_regfile.sv
rtl/fa_scheduler.sv
rtl/fa_dot_pe.sv
rtl/fa_score_scale.sv
rtl/fa_score_pipe.sv
rtl/fa_row_engine.sv
rtl/fa_compute_core.sv
rtl/fa_exp_approx.sv
rtl/fa_recip_approx.sv
rtl/fa_softmax_online.sv
rtl/fa_softmax_online_vec.sv
rtl/fa_finalize_vec.sv
rtl/fa_out_quant.sv
rtl/fa_dma_rd.sv
rtl/fa_dma_wr.sv
sky130_sram_macros/verilog/sky130_sram_0kbytes_1rw1r_32x64_8.v
sky130_sram_macros/verilog/sky130_sram_0kbytes_1rw1r_48x16_8.v
rtl/fa_sram_macros.v
rtl/fa_q_buffer.sv
rtl/fa_kv_buffer.sv
rtl/fa_group_engine.sv
rtl/fa_o_group_store.sv
rtl/fa_accel_top.sv
