../RTL/fa_pkg.sv
../RTL/fa_regfile.sv
../RTL/fa_scheduler.sv
../RTL/fa_dot_pe.sv
../RTL/fa_score_scale.sv
../RTL/fa_score_pipe.sv
../RTL/fa_row_engine.sv
../RTL/fa_compute_core.sv
../RTL/fa_exp_approx.sv
../RTL/fa_recip_approx.sv
../RTL/fa_softmax_online.sv
../RTL/fa_softmax_online_vec.sv
../RTL/fa_out_quant.sv
../RTL/fa_finalize_vec.sv
../RTL/fa_dma_rd.sv
../RTL/fa_dma_wr.sv
../RTL/sky130_sram_macro_blackboxes.v
../RTL/fa_sram_macros.v
../RTL/fa_q_buffer.sv
../RTL/fa_kv_buffer.sv
../RTL/fa_accel_top.sv
