/home/hujinzhao/pro/genus_bs1/workspace/RTL/fa_top.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/dot_frontend.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/packed_compute_core.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/score_scheduler.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/score_exp_pipe.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/score_exp_banked_rom.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/output_norm_pipe.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/reciprocal_approx.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/finalize_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/update_state_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/update_token_fifo.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/axi_lite_regs.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/task_ctrl.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/dma_engine.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/dma_cmd_queue.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/dma_read_master.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/dma_write_master.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/q_load_store_adapter.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/qk_sram_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/v_load_adapter.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/k_load_adapter.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/o_store_adapter.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/v_sram_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/acc_sram_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/meta_sram_cluster.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/page_manager.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/perf_counters.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/sky130_sram_0kbytes_1rw1r_64x32_8_wrapper.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/sky130_sram_0kbytes_1rw1r_128x16_16_timed_wrapper.v
/home/hujinzhao/pro/genus_bs1/workspace/RTL/sky130_sram_0kbytes_1rw1r_64x64_8_wrapper.v
