../RTL/fa_top.v
../RTL/dot_frontend.v
../RTL/packed_compute_core.v
../RTL/score_scheduler.v
../RTL/score_exp_pipe.v
../RTL/score_exp_banked_rom.v
../RTL/output_norm_pipe.v
../RTL/reciprocal_approx.v
../RTL/finalize_cluster.v
../RTL/update_state_cluster.v
../RTL/update_token_fifo.v
../RTL/axi_lite_regs.v
../RTL/task_ctrl.v
../RTL/dma_engine.v
../RTL/dma_cmd_queue.v
../RTL/dma_read_master.v
../RTL/dma_write_master.v
../RTL/q_load_store_adapter.v
../RTL/qk_sram_cluster.v
../RTL/v_load_adapter.v
../RTL/k_load_adapter.v
../RTL/o_store_adapter.v
../RTL/v_sram_cluster.v
../RTL/acc_sram_cluster.v
../RTL/meta_sram_cluster.v
../RTL/page_manager.v
../RTL/perf_counters.v
../RTL/sky130_sram_0kbytes_1rw1r_64x64_8_wrapper.v
